[package]
name = "tmt-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
repository.workspace = true

[dependencies]
roxmltree.workspace = true
serde_json.workspace = true
tmt-cli-style.workspace = true
taffy.workspace = true

[lints]
workspace = true
