export const browserUiClasses = Object.freeze({
  command: 'tmt-ui-command',
  commandText: 'tmt-ui-command-text',
  commandCopy: 'tmt-ui-command-copy',
  commandFeedback: 'tmt-ui-command-feedback',
  code: 'tmt-ui-code',
  header: 'tmt-ui-header',
  brand: 'tmt-ui-brand',
  mark: 'tmt-ui-mark',
  wordmark: 'tmt-ui-wordmark',
  heading: 'tmt-ui-heading',
  title: 'tmt-ui-title',
  caption: 'tmt-ui-caption',
  status: 'tmt-ui-status',
  actions: 'tmt-ui-actions',
  icon: 'tmt-ui-icon',
  notice: 'tmt-ui-notice',
  noticeMark: 'tmt-ui-notice-mark',
  noticeEyebrow: 'tmt-ui-notice-eyebrow',
  noticeHeading: 'tmt-ui-notice-heading',
  noticeBody: 'tmt-ui-notice-body',
  noticeActions: 'tmt-ui-notice-actions',
  field: 'tmt-ui-field',
  fieldLabel: 'tmt-ui-field-label',
  fieldControl: 'tmt-ui-field-control',
  fieldDescription: 'tmt-ui-field-description',
  fieldError: 'tmt-ui-field-error',
  action: 'tmt-ui-action',
  actionLabel: 'tmt-ui-action-label',
  actionMark: 'tmt-ui-action-mark',
  iconAction: 'tmt-ui-icon-action',
  iconActionControl: 'tmt-ui-icon-action-control',
  iconActionIcon: 'tmt-ui-icon-action-icon',
  iconActionTooltip: 'tmt-ui-icon-action-tooltip',
  iconActionTooltipLabel: 'tmt-ui-icon-action-tooltip-label',
  toggle: 'tmt-ui-toggle',
  toggleIndicator: 'tmt-ui-toggle-indicator',
  list: 'tmt-ui-list',
  listRow: 'tmt-ui-list-row',
  listTitle: 'tmt-ui-list-title',
  listMeta: 'tmt-ui-list-meta',
  listUpdated: 'tmt-ui-list-updated',
  listState: 'tmt-ui-list-state',
  listActions: 'tmt-ui-list-actions',
} as const);

export type BrowserNoticeTone = 'waiting' | 'blocked' | 'working' | 'review' | 'muted';
export type BrowserActionVariant = 'text' | 'primary' | 'destructive';
export type BrowserAnnouncement = 'status' | 'alert' | 'none';
