//! Commands that do not yet follow the help style, with the rules each still
//! breaks. #436 PR 2a migrates the core commands; Office's commands stay
//! listed until #355 resumes. The list only shrinks and is empty at the end:
//! the guard fails when a listed command already follows the style.

use tmt_cli_style::audit::Rule::{self, *};

pub const MIGRATING: &[(&str, &[Rule])] = &[
    // Core. The root also prints its preamble outside the template.
    ("tmt add", &[Template, Examples]),
    ("tmt api", &[Template, Examples]),
    ("tmt check", &[Template, Examples]),
    ("tmt completion", &[Template, Examples]),
    ("tmt config clear", &[Template, Examples]),
    ("tmt config set", &[Template, Examples]),
    ("tmt config show", &[Template, Examples]),
    ("tmt config", &[Template, Examples]),
    ("tmt extension hooks disable", &[Template, Examples]),
    ("tmt extension hooks enable", &[Template, Examples]),
    ("tmt extension hooks list", &[Template, Examples]),
    ("tmt extension hooks", &[Template, Examples]),
    ("tmt extension install", &[Template, Examples]),
    ("tmt extension list", &[Template, Examples]),
    ("tmt extension uninstall", &[Template, Examples]),
    ("tmt extension upgrade", &[Template, Examples]),
    ("tmt extension", &[Template, Examples]),
    ("tmt focus", &[Template, Examples]),
    ("tmt help", &[Template, Examples]),
    ("tmt identity create", &[Template, Examples]),
    ("tmt identity list", &[Template, Examples]),
    ("tmt identity meta get", &[Template, Examples]),
    ("tmt identity meta list", &[Template, Examples]),
    ("tmt identity meta rm", &[Template, Examples]),
    ("tmt identity meta set", &[Template, Examples]),
    ("tmt identity meta", &[Template, Examples]),
    ("tmt identity show", &[Template, Examples]),
    ("tmt identity status clear", &[Template, Examples]),
    ("tmt identity status set", &[Template, Examples]),
    ("tmt identity status show", &[Template, Examples]),
    ("tmt identity status", &[Template, Examples]),
    ("tmt identity", &[Template, Examples]),
    ("tmt init", &[Template, Examples]),
    ("tmt install", &[Template, Examples]),
    ("tmt learn", &[Template, Examples]),
    ("tmt list", &[Template, Examples]),
    ("tmt marked", &[Template, Examples]),
    ("tmt name", &[Template, Examples]),
    ("tmt notes path", &[Template, Examples]),
    ("tmt notes", &[Template, Examples]),
    ("tmt preamble clear", &[Template, Examples]),
    ("tmt preamble set", &[Template, Examples]),
    ("tmt preamble show", &[Template, Examples]),
    ("tmt preamble", &[Template, Examples]),
    ("tmt reply", &[Template, Examples]),
    ("tmt result", &[Template, Examples]),
    ("tmt resume", &[Template, Examples]),
    ("tmt rm", &[Template, Examples]),
    ("tmt role clear", &[Template, Examples]),
    ("tmt role set", &[Template, Examples]),
    ("tmt role show", &[Template, Examples]),
    ("tmt role", &[Template, Examples]),
    ("tmt room broadcast", &[Template, Examples]),
    ("tmt room create", &[Template, Examples]),
    ("tmt room join", &[Template, Examples]),
    ("tmt room leave", &[Template, Examples]),
    ("tmt room list", &[Template, Examples]),
    ("tmt room retire", &[Template, Examples]),
    ("tmt room send", &[Template, Examples]),
    ("tmt room show", &[Template, Examples]),
    ("tmt room", &[Template, Examples]),
    ("tmt run", &[Template, Examples]),
    ("tmt setup", &[Template, Examples]),
    ("tmt talk", &[Template, Examples]),
    ("tmt unbind", &[Template, Examples]),
    ("tmt upgrade", &[Template, Examples]),
    ("tmt whoami", &[Template, Examples]),
    ("tmt x ack", &[Template, Examples]),
    ("tmt x ackall", &[Template, Examples]),
    ("tmt x list", &[Template, Examples]),
    ("tmt x listen", &[Template, Examples]),
    ("tmt x show", &[Template, Examples]),
    ("tmt x", &[Template, Examples]),
    ("tmt", &[Template, Examples]),
    // Office, reached through the reserved facade (#355).
    ("tmt office", &[Template, Examples]),
    ("tmt office avatar", &[Template, Examples]),
    ("tmt office avatar install", &[Template, Examples]),
    ("tmt office avatar list", &[Template, Examples]),
    ("tmt office avatar preview", &[Template, Examples]),
    ("tmt office avatar remove", &[Template, Examples]),
    ("tmt office avatar show", &[Template, Examples]),
    ("tmt office avatar validate", &[Template, Examples]),
    ("tmt office block", &[Template, Examples]),
    ("tmt office block apply", &[Template, Examples]),
    ("tmt office block show", &[Template, Examples]),
    ("tmt office board", &[Template, Examples]),
    ("tmt office board delete", &[Template, Examples]),
    ("tmt office board edit", &[Template, Examples]),
    ("tmt office board list", &[Template, Examples]),
    ("tmt office board post", &[Template, Examples]),
    ("tmt office board reply", &[Template, Examples]),
    ("tmt office board show", &[Template, Examples]),
    ("tmt office extension", &[Template, Examples]),
    ("tmt office extension validate", &[Template, Examples]),
    ("tmt office inspect", &[Template, Examples]),
    ("tmt office install", &[Template, Examples]),
    ("tmt office layout", &[Template, Examples]),
    ("tmt office layout apply", &[Template, Examples]),
    ("tmt office layout show", &[Template, Examples]),
    ("tmt office pair", &[Template, Examples]),
    ("tmt office profile", &[Template, Examples]),
    ("tmt office profile apply", &[Template, Examples]),
    ("tmt office profile show", &[Template, Examples]),
    ("tmt office prop", &[Template, Examples]),
    ("tmt office prop install", &[Template, Examples]),
    ("tmt office prop list", &[Template, Examples]),
    ("tmt office prop preview", &[Template, Examples]),
    ("tmt office prop remove", &[Template, Examples]),
    ("tmt office prop show", &[Template, Examples]),
    ("tmt office prop validate", &[Template, Examples]),
    ("tmt office start", &[Template, Examples]),
    ("tmt office status", &[Template, Examples]),
    ("tmt office stop", &[Template, Examples]),
    ("tmt office storage", &[Template, Examples]),
    ("tmt office storage migrate", &[Template, Examples]),
    ("tmt office storage status", &[Template, Examples]),
    ("tmt office sync", &[Template, Examples]),
    ("tmt office uninstall", &[Template, Examples]),
    ("tmt office unpair", &[Template, Examples]),
    ("tmt office upgrade", &[Template, Examples]),
    ("tmt office whiteboard", &[Template, Examples]),
    ("tmt office whiteboard snapshot", &[Template, Examples]),
    (
        "tmt office whiteboard snapshot export",
        &[Template, Examples],
    ),
    ("tmt office whiteboard snapshot show", &[Template, Examples]),
];
