import { expect, it } from 'vite-plus/test';
import { readFileSync, mkdtempSync, mkdirSync, cpSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { browserUiClasses } from '../src/static';

it('exports frozen static names and an exact non-writing generated stylesheet', () => {
  expect(Object.isFrozen(browserUiClasses)).toBe(true);
  const file = new URL('../generated/static.css', import.meta.url);
  const before = readFileSync(file, 'utf8');
  execFileSync(process.execPath, [
    new URL('../scripts/generate-static-css.mjs', import.meta.url).pathname,
    '--check',
  ]);
  expect(readFileSync(file, 'utf8')).toBe(before);
  for (const name of Object.values(browserUiClasses)) expect(before).toContain(`.${name}`);
  expect(before).not.toMatch(/rgba?\(|hsla?\(|opacity:\s*0/);
  expect(
    [...before.matchAll(/box-shadow:\s*([^;]+);/g)].every((match) => match[1] === 'none'),
  ).toBe(true);
  expect(before).not.toMatch(/(?:^|\n)(?:body|input|button|h[12]|\*)\s*[{,]/);
  expect(before).toContain("[data-theme='dark']");
  expect(before).toContain('--tmt-ui-header-height: 56px');
  expect(before).toContain('--tmt-ui-header-compact-height: 48px');
});

it('refuses stale and missing generated bytes without repairing them', () => {
  const root = mkdtempSync(path.join(tmpdir(), 'browser-ui-equality-'));
  try {
    const home = path.join(root, 'design/browser-ui');
    mkdirSync(path.dirname(home), { recursive: true });
    cpSync(new URL('..', import.meta.url), home, {
      recursive: true,
      filter: (file) => !file.endsWith('node_modules'),
    });
    cpSync(new URL('../../tokens', import.meta.url), path.join(root, 'design/tokens'), {
      recursive: true,
    });
    const generated = path.join(home, 'generated/static.css');
    const command = [path.join(home, 'scripts/generate-static-css.mjs'), '--check'];
    writeFileSync(generated, 'stale bytes');
    expect(() => execFileSync(process.execPath, command, { stdio: 'pipe' })).toThrow();
    expect(readFileSync(generated, 'utf8')).toBe('stale bytes');
    rmSync(generated);
    expect(() => execFileSync(process.execPath, command, { stdio: 'pipe' })).toThrow();
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
