/** English chrome catalog; page content and fixture text are not UI strings. */
/** A size as a person reads it, and exactly: 2.5 MiB (2,621,440 bytes). */
function formatBytes(bytes: number): string {
  const [value, unit] =
    bytes >= 1024 * 1024 ? [bytes / (1024 * 1024), 'MiB'] : [bytes / 1024, 'KiB'];
  return `${value.toFixed(2).replace(/\.?0+$/, '')} ${unit} (${bytes.toLocaleString('en-US')} bytes)`;
}

/** One short size a person reads: 18 bytes, 2.4 KB, 8 MB. */
function humanSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} ${bytes === 1 ? 'byte' : 'bytes'}`;
  const [value, unit] = bytes >= 1024 * 1024 ? [bytes / (1024 * 1024), 'MB'] : [bytes / 1024, 'KB'];
  return `${value.toFixed(1).replace(/\.0$/, '')} ${unit}`;
}

export const text = {
  unknownPageTitle: 'Untitled page',
  originalAuthor: 'Original author',
  byAuthor: (name: string) => `By ${name}`,
  unknownAuthor: 'Unknown author',
  latestPublisher: 'Latest publisher',
  authorAttributionNote:
    'Names are publisher-provided labels, not proof of identity or permission.',
  messageLabel: 'Message',
  newMessages: 'New messages',
  annotationTitle: 'Annotate',
  annotationClose: 'Close annotation',
  messagePlaceholder: 'Write a message…',
  messageUnavailable: 'Sending is unavailable right now.',
  messageAgentsUnavailable: 'Agents are unavailable.',
  messageCommentAvailable: 'You can still post a comment.',
  messageAgentsChecking: 'Checking for agents…',
  messageAgentsRetry: 'Try again',
  messageWrite: 'Write a message.',
  messageSending: 'Sending…',
  messageComment: 'Posts as a comment.',
  messageAsks: (audience: string) => `Asks ${audience}.`,
  messageUnknown: (name: string, audience: string) =>
    `No agent named @${name}. ${audience ? `Asks ${audience}.` : 'This posts as a comment.'}`,
  messageAmbiguous: (name: string) => `Several agents are named @${name}. Choose one.`,
  messageRecipientUnavailable: (name: string) =>
    `@${name} is unavailable. Remove the mention to post.`,
  messageRecipientLimit: 'Mention up to 8 agents per message.',
  messageAgentsEmpty: 'No agents are available. This posts as a comment.',
  messageAskAgain: (name: string) => `Mention @${name} in a new message to ask again.`,
  messageRecordedDeliveryFailed: 'Delivery failed. The recorded turn was kept.',
  messageRecordedUncertain:
    'The turn was recorded, but delivery is unavailable or uncertain. Check the thread before sending again.',
  messageRecordFailed: 'The turn could not be recorded.',
  messageAnother: 'Write another message',
  messageOpenRecorded: 'Open recorded thread',
  draftsNotSaved: 'Drafts are not saved on this device.',
  attachFiles: 'Attach files',
  attachFilesHint: 'Files upload when you send. Nothing is sent until then.',
  attachListLabel: 'Attachments to send',
  attachReady: 'Uploads on send',
  attachUploading: (percent: number) => `Uploading ${percent}%`,
  attachStored: 'Uploaded',
  attachAgainPageChanged: 'The page changed. Send to upload it again.',
  attachAgainNotStored: 'No longer stored. Send to upload it again.',
  attachUnknown: 'Upload not confirmed.',
  attachCheck: 'Check again',
  attachRetry: 'Try again',
  attachRemove: 'Remove',
  attachDismiss: 'Dismiss',
  attachRefused: {
    'too-large': 'Too large to store.',
    unavailable: 'Storage is unavailable.',
    denied: 'Not allowed on this page.',
    capacity: 'Storage is full.',
    invalid: 'Could not be stored.',
    conflict: 'Could not be stored.',
  },
  attachNotice: {
    empty: (name: string) => `${name} is empty.`,
    'too-large': (name: string) =>
      `${name} is larger than ${humanSize(8 * 1024 * 1024)}, the limit per file.`,
    'too-many': (name: string) => `${name} was not added. A message holds up to 16 files.`,
    unreadable: (name: string) => `${name} could not be read.`,
  },
  attachBlocked: {
    unknown: 'Your message was not sent. Check or remove the unconfirmed upload.',
    refused: 'Your message was not sent. Remove the refused file or try again.',
    failed: 'Your message was not sent. A file could not be attached.',
    stale:
      'Your message was not sent. The page changed while attaching; send again to upload the files.',
  },
  files: 'Files',
  filesEmpty: 'No files yet.',
  filesListLabel: 'Page files',
  filesAdd: 'Add to page',
  filesAdding: 'Adding…',
  filesReady: 'Ready to add',
  filesAgainPageChanged: 'The page changed. Add to upload it again.',
  filesAgainNotStored: 'No longer stored. Add to upload it again.',
  filesTooMany: (name: string) => `${name} was not added. Add up to 16 files at a time.`,
  filesFull: 'A page holds up to 128 files. Remove one to add more.',
  filesRemoving: 'Removing…',
  filesRemoveFailed: 'Could not remove this file.',
  filesBlocked: {
    unknown: 'Files were not added. Check or remove the unconfirmed upload.',
    refused: 'Files were not added. Remove the refused file or try again.',
    failed: 'Files were not added. A file could not be uploaded.',
    stale: 'Files were not added. The page changed while uploading; add them again.',
    save: 'Files were not added. The page could not be saved; add them again.',
  },
  messageAttachmentsLabel: 'Attached files',
  attachmentDownload: 'Download',
  attachmentPreview: 'Preview',
  attachmentHidePreview: 'Hide preview',
  attachmentOpening: 'Opening…',
  attachmentUnavailable: 'This file is unavailable.',
  attachmentReason: {
    denied: 'You can no longer open this file.',
    'not-found': 'This file is no longer on this page.',
    changed: 'The page changed while opening. Try again.',
    unavailable: 'This file is unavailable.',
  },
  attachmentSize: humanSize,
  savedDrafts: 'Saved drafts',
  savedDraftQuote: 'Select this quote again to continue.',
  savedDraftThreadGone: 'The thread for this draft is no longer available.',
  savedDraftDiscard: 'Discard draft',
  askShort: 'Ask',
  comments: 'Comments',
  commentSelection: 'Comment on selection',
  commentPage: 'Comment on page',
  commentPost: 'Post comment',
  commentReply: 'Reply',
  commentPostReply: 'Post reply',
  commentEmpty: 'No comments yet. Select text to start a thread, or comment on the page.',
  commentDevice: 'Commenting device',
  commentEdited: 'edited',
  commentDeleted: 'Comment deleted',
  commentEdit: 'Edit',
  commentEditBody: 'Edit comment',
  commentSave: 'Save comment',
  commentDelete: 'Delete comment',
  commentCancel: 'Cancel',
  commentFailed:
    'Could not save this change. Your draft is kept. Reconnect and review the latest discussion.',
  commentAnchored: 'Attached',
  commentDetached: 'Detached',
  commentQuoteChanged: 'This text changed on the page; your note keeps the original quote.',
  commentReattach: 'Reattach to selection',
  commentConfirmReattach: 'Confirm reattach',
  threadOpen: 'Open',
  threadResolved: 'Resolved',
  threadDeleted: 'Deleted thread',
  threadResolve: 'Resolve',
  threadReopen: 'Reopen',
  threadResolvedBy: (name: string) => `Resolved by ${name}`,
  threadUnseen: 'New',
  threadNotNotified: (names: string) => `Not notified: ${names}`,
  threadClose: 'Close thread',
  threadDelete: 'Delete thread',
  conversationAgent: 'agent',
  reconnect: 'Reconnect',
  disconnected: 'Disconnected',
  connectionLost: 'Connection lost',
  recoveryRequired: 'Reconnect to resume live updates.',
  reconnecting: 'Reconnecting…',
  reconnectToSend: 'Reconnect to send.',
  reconnectFailed:
    'Could not reconnect. Open this page from a paired browser, or pair with tmt remote pair.',
  sessionEvicted: (limit: number) =>
    `This tab was disconnected when your paired device reached its limit of ${limit} Remote sessions.`,
  sessionLimitCommand: 'To allow another tab, run:',
  remoteSettings: 'Open Remote settings',
  ask: 'Ask agent',
  asks: 'Page asks',
  askSelection: 'Select text in the page to ask your agent.',
  askComment: 'Question or instruction',
  askPick: 'Choose an agent on your machine',
  askLoading: 'Loading your agents…',
  askNone: 'No agents are available on your machine.',
  askPreviewFailed: 'Could not prepare the preview. Refresh your agents and try again.',
  askRefresh: 'Refresh agents',
  askOffline: 'Your machine or page connection is offline. Reconnect and review a new preview.',
  askExpired: 'This preview has expired. Create a new preview before sending.',
  askRecheck: 'Check again',
  chatVisible: 'Visible to everyone with page access.',
  askWaiting: (agent: string) => `Waiting for ${agent}`,
  askNoReply: (agent: string) => `No reply yet from ${agent}`,
  askApproval: 'Waiting for approval',
  askNotDelivered: 'Not delivered',
  askUnconfirmed: 'Delivery unconfirmed',
  askTrackingAbandoned: 'Tracking abandoned',
  askResultUnavailable: 'Result unavailable',
  askAbandon: 'Abandon tracking',
  askActionFailed: 'Could not update this ask. Its delivery may still be uncertain.',
  askEmpty: 'No asks on this page yet.',
  askReply: 'Agent reply',
  askDeliveryAccepted: 'Accepted by your machine.',
  askReplyFrom: 'Reply from',
  askAgentLabel: 'Agent',
  askDeviceLabel: 'Asking device',
  askYou: 'You',
  askJustNow: 'Just now',
  askCreated: 'Ask created:',
  askDetails: 'Details',
  askOperation: 'Operation',
  askEmptyReply: 'The agent returned an empty reply.',
  askAbandoned: 'Tracking abandoned. The work may still have been delivered.',
  askExpiredState: 'This ask expired before delivery.',
  askDispatching: 'Sending to your machine…',
  askObservationUnavailable: 'Could not observe agent results. Check again to resume.',
  askOperationFailed: 'This send failed.',
  askFinalUnavailable: 'The agent result is unavailable.',
  askScopeDenied: 'Your Remote permission does not allow this ask.',
  askInputInvalid: 'Remote rejected this message. Write a new message.',
  askRateLimited: 'Remote is busy. Try a new message later.',
  askIntentConflict: 'This operation already has a different message. Write a new message.',
  askRemoteClosed: 'Remote is closed. Reconnect before writing another message.',
  askSessionEnded: 'Your Remote session ended. Reconnect before writing another message.',
  askInputTooLarge: 'Remote rejected the message size. Write a shorter message.',
  askStateUnavailable: 'Remote cannot read this operation yet. Check again later.',
  askCoreUnavailable: 'The agent service is unavailable. Check again later.',
  askPreview: 'Ask agent — preview',
  askMachine: 'Your machine',
  askAgent: 'Agent',
  askMessage: 'Exact message',
  askVisible: 'Your ask and the agent’s reply are visible to everyone who can see this page.',
  askHold: 'This send waits for approval on your machine.',
  askEscaped: 'Show hidden characters',
  askAdaptation:
    "Terminal delivery may escape '!' characters; the agent still receives the exact text above.",
  askUnavailable: 'Agent sending is unavailable for this page.',
  askSend: 'Send',
  askClose: 'Close preview',
  agentStatus: 'Agents',
  agentStatusRecheck: 'Recheck status',
  agentStatusPage: 'Colab page',
  agentStatusSession: 'Remote session',
  agentStatusDirectory: 'Agent directory',
  agentStatusAdmitted: 'Admitted',
  agentStatusRead: 'Read succeeded',
  agentStatusChecking: 'Checking…',
  agentStatusUnavailable: 'Read unavailable',
  agentStatusRefused: 'Read refused',
  agentStatusChannelUnavailable: 'Session channel unavailable',
  agentStatusEnded: 'Session ended',
  agentStatusEvicted: 'Session limit reached',
  agentStatusEmpty: 'No admitted agents in this directory.',
  agentStatusActive: 'Active',
  agentStatusLastCheck: 'Last successful check',
  agentStatusStale: 'Previous snapshot · current presence is unavailable',
  agentStatusNoRead: 'No successful directory read yet.',
  agentStatusReadOnly: 'Checking status does not send messages or reopen a session.',
  presenceOnline: 'Online',
  presenceOffline: 'Offline',
  presenceUnknown: 'Unknown',
  online: 'Online',
  offline: 'Offline',
  unknown: 'Online state unavailable',
  channel: 'Channel ready',
  paste: 'Paste only',
  not_ready: 'Not ready',
  not_running: 'Not running',
  deliveryUnknown: 'Delivery status unavailable',
  askPreparing: 'Preparing send…',
  askFailed: 'Could not prepare this send. Nothing was sent.',
  askHeld: 'Waiting for approval on your machine.',
  askAccepted: 'Accepted; awaiting the agent’s reply.',
  askUncertain: 'Delivery is uncertain. The work may have been delivered. Do not resend.',
  askRefused: 'The send was refused.',
  askCancelled: 'The send was cancelled.',
  export: 'Export page',
  download: 'Download',
  exportUnavailable: 'Export requires a verified paired page.',
  exportDiscussions:
    'Includes the comments and Ask conversations visible on this page, as of this copy.',
  exportPreparing: 'Preparing an exact copy of the verified page…',
  exportFailed:
    'Could not prepare or request this download. Already requested files may have downloaded.',
  exportReady: 'Download the files. This copy stays fixed while the live page changes.',
  exportPartial: 'Some files requested. Download the others to complete this copy.',
  exportRequested: 'All downloads requested. Check your browser downloads for the saved files.',
  exportClose: 'Close export',
  product: 'Colab',
  local: 'Local preview',
  mounted: 'Paired space',
  mountedNote: 'Connected through your paired Remote session.',
  registering: 'Opening your paired space…',
  registrationFailed: 'Could not open this paired space. Reload to retry.',
  pinMismatch:
    'This address does not match the pinned space. Return to the original space address.',
  noWraps: 'This device has no verified page key yet. The page remains blocked.',
  save: 'Save source',
  saving: 'Saving…',
  editFailed:
    'The edit was not saved. Reopen the page to review the latest source before trying again.',
  saveTooLarge: (size: number, limit: number) =>
    `The source is ${formatBytes(size)}, over the ${formatBytes(limit)} one page can hold. Shorten it, then save again.`,
  saveStale:
    'The page changed while you were editing, so nothing was saved. Copy your changes, reload to get the latest source, then apply them again.',
  saveNotSaved: 'Not saved',
  saveUnconfirmed: 'Unconfirmed',
  saveNotApplied: 'The save did not reach the page, so nothing changed. Save again.',
  saveUnknown: (operationId: string) =>
    `The connection dropped before the save was confirmed. Copy your changes, then reload to see whether they were saved. Reference: ${operationId}`,
  reload: 'Reload',
  updated: 'Colab has been updated.',
  /** One sentence in three parts so the command can be shown as code. */
  serveOlder: {
    lead: (installed: string, running: string) =>
      `Colab ${installed} is installed, but ${running} is still running.`,
    restart: 'Restart',
    command: 'tmt colab serve',
    tail: 'to update.',
  },
  pages: 'Pages',
  shared: 'Shared',
  archived: 'Archived',
  showArchived: 'Show archived',
  updateTimeUnknown: 'Update time unknown',
  lastUpdated: 'Last updated',
  pageActions: 'Actions',
  pageActionsFor: (title: string) => `Actions for ${title}`,
  home: 'Space home',
  intro: 'A place for pages you share.',
  open: 'Open page',
  empty:
    'No pages in this space yet. Create one on your machine with tmt colab page create --title "Notes".',
  private: 'Private',
  link: 'Link',
  public: 'Public',
  theme: 'Change color theme',
  source: 'Source',
  preview: 'Preview',
  loading: 'Opening page…',
  loaded: 'Live preview',
  boundary: 'Page content',
  error: 'Page unavailable',
  retry: 'Return to space',
  blocked: 'Preview stopped',
  failureAccessEnded: 'Your access to this page ended. Open it again to continue.',
  failurePageGone: 'This page is no longer available. It may have been deleted.',
  failureSessionEnded: 'The Remote session for this page ended. Reopen the page to continue.',
  failureTooLarge: 'This change is too large to sync. Reopen the page and make a smaller change.',
  failureGeneric: 'This page stopped syncing. Reopen it to try again.',
  failureCodeLabel: 'Code:',
  navigation: 'The page navigated. Reopen it to continue.',
  failed: 'The renderer could not start. Reopen the page to try again.',
  limit: 'This preview accepts pages up to 2 MiB of HTML.',
  warning:
    'Page scripts run inside an isolated frame. A page can navigate its own frame; complete exfiltration prevention is not guaranteed.',
  adapter: 'This preview uses local sample pages. It is not connected to a remote space.',
  readerOnly: 'Read-only',
  readerLive: 'Live',
  readerLoading: 'Opening',
  readerStopped: 'Stopped',
  readerInfo: 'Info',
  readerOpening: 'Opening shared page…',
  readerEnded: 'Access ended',
  readerEndedNote: 'This link no longer gives access to the page. Ask the owner for a new link.',
  readerInvalid: 'This link is incomplete or malformed. Open the full link again.',
  readerFailed: 'Could not open this page. Open the full link again.',
  readerNote:
    'You are reading a shared page. You cannot edit it or ask agents. Anyone who holds this link and can reach this address can read the page.',
} as const;
