/** English chrome catalog; page content and fixture text are not UI strings. */
export const text = {
  askPreview: 'Ask agent — preview',
  askMachine: 'Your machine',
  askAgent: 'Agent',
  askMessage: 'Exact message',
  askVisible: 'Your ask and the agent’s reply are visible to everyone who can see this page.',
  askHold: 'This send waits for approval on your machine.',
  askEscaped: 'Show hidden characters',
  askAdaptation:
    'TMT may protect ! during terminal delivery; the signed and stored message stays unchanged.',
  askUnavailable: 'Agent sending is not available in this preview yet.',
  askSend: 'Send',
  askClose: 'Close preview',
  online: 'Online',
  offline: 'Offline',
  unknown: 'Online state unavailable',
  channel: 'Channel ready',
  paste: 'Paste only',
  not_ready: 'Not ready',
  not_running: 'Not running',
  deliveryUnknown: 'Delivery status unavailable',
  askPreparing: 'Preparing send…',
  askFailed: 'Could not prepare this send. Nothing was sent.',
  askHeld: 'Waiting for approval on your machine.',
  askAccepted: 'Accepted; awaiting the agent’s reply.',
  askUncertain: 'Delivery is uncertain. The work may have been delivered. Do not resend.',
  askRefused: 'The send was refused.',
  askCancelled: 'The send was cancelled.',
  export: 'Export page',
  download: 'Download',
  exportUnavailable: 'Export requires a verified paired page.',
  exportDiscussions: 'Discussions are not included.',
  exportPreparing: 'Preparing an exact copy of the verified page…',
  exportFailed:
    'Could not prepare or request this download. Already requested files may have downloaded.',
  exportReady: 'Download both files. This copy stays fixed while the live page changes.',
  exportPartial: 'One file requested. Download the other file to complete this copy.',
  exportRequested: 'Both downloads requested. Check your browser downloads for the saved files.',
  exportClose: 'Close export',
  product: 'Colab',
  local: 'Local preview',
  mounted: 'Paired space',
  mountedNote: 'Connected through your paired Remote session.',
  registering: 'Opening your paired space…',
  registrationFailed: 'Could not open this paired space. Reload to retry.',
  pinMismatch:
    'This address does not match the pinned space. Return to the original space address.',
  noWraps: 'This device has no verified page key yet. The page remains blocked.',
  save: 'Save source',
  saving: 'Saving…',
  editFailed:
    'The edit was not saved. Reopen the page to review the latest source before trying again.',
  ownNotDisplayed:
    'This page contains authenticated own data. Comments and activity are not displayed yet.',
  reload: 'Reload',
  pages: 'Pages',
  home: 'Space home',
  intro: 'A place for pages you share.',
  open: 'Open page',
  empty:
    'No pages in this space yet. Create one on your machine with tmt colab page create --title "Notes".',
  private: 'Private',
  link: 'Link',
  public: 'Public',
  theme: 'Change color theme',
  source: 'Source',
  preview: 'Preview',
  loading: 'Opening page…',
  loaded: 'Live preview',
  boundary: 'Page content',
  error: 'Page unavailable',
  retry: 'Return to space',
  blocked: 'Preview stopped',
  navigation: 'The page navigated. Reopen it to continue.',
  failed: 'The renderer could not start. Reopen the page to try again.',
  limit: 'This preview accepts pages up to 2 MiB of HTML.',
  warning:
    'Page scripts run inside an isolated frame. A page can navigate its own frame; complete exfiltration prevention is not guaranteed.',
  adapter: 'This preview uses local sample pages. It is not connected to a remote space.',
} as const;
