//! Directory-handle traversal of one extension's private object tree. Every
//! component is opened relative to an admitted parent handle with no-follow, and
//! every directory and file is checked on its own handle (owner, mode, type), so
//! a path is never validated and then reopened. Names are only the fixed tree
//! names and 64-hex identifiers generated by the owner; nothing here accepts a
//! caller path or lists a directory.
use nix::{
    errno::Errno,
    fcntl::{AtFlags, OFlag, openat},
    sys::stat::{Mode, mkdirat},
    unistd::{Uid, UnlinkatFlags, linkat, unlinkat},
};
use std::{
    fs::File,
    io,
    os::unix::fs::{FileExt, MetadataExt},
    path::Path,
};

#[derive(Debug)]
pub enum TreeError {
    /// A symlink, wrong owner/mode/type, unexpected link count or foreign entry.
    Unsafe,
    /// An operating-system failure; the backend reports it as unavailable storage.
    Io,
}
impl From<io::Error> for TreeError {
    fn from(_: io::Error) -> Self {
        Self::Io
    }
}
impl From<Errno> for TreeError {
    fn from(errno: Errno) -> Self {
        match errno {
            Errno::ELOOP | Errno::ENOTDIR | Errno::EISDIR | Errno::ENXIO => Self::Unsafe,
            _ => Self::Io,
        }
    }
}
type Result<T> = std::result::Result<T, TreeError>;

/// A name this owner generates: a fixed tree name or 64 lowercase hex digits.
pub fn valid_name(name: &str) -> bool {
    matches!(name, "objects" | "staging" | "blobs")
        || (name.len() == 64 && name.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f')))
}
pub fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// An admitted owned 0700 directory, held open.
pub struct Dir(File);
impl Dir {
    /// Admit the extension subtree root without following a final symlink.
    pub fn open_root(path: &Path) -> Result<Self> {
        let fd = openat(
            nix::fcntl::AT_FDCWD,
            path,
            OFlag::O_RDONLY | OFlag::O_DIRECTORY | OFlag::O_NOFOLLOW | OFlag::O_CLOEXEC,
            Mode::empty(),
        )?;
        Self::admit(File::from(fd))
    }
    fn admit(file: File) -> Result<Self> {
        let metadata = file.metadata()?;
        if !metadata.is_dir()
            || metadata.uid() != Uid::effective().as_raw()
            || metadata.mode() & 0o777 != 0o700
        {
            return Err(TreeError::Unsafe);
        }
        Ok(Self(file))
    }
    /// An existing child directory, or `None`; with `create` a missing one is
    /// made 0700 and the parent synced before it is used.
    pub fn child(&self, name: &str, create: bool) -> Result<Option<Self>> {
        debug_assert!(valid_name(name));
        let open = || {
            openat(
                &self.0,
                name,
                OFlag::O_RDONLY | OFlag::O_DIRECTORY | OFlag::O_NOFOLLOW | OFlag::O_CLOEXEC,
                Mode::empty(),
            )
        };
        match open() {
            Ok(fd) => return Self::admit(File::from(fd)).map(Some),
            Err(Errno::ENOENT) if create => {}
            Err(Errno::ENOENT) => return Ok(None),
            Err(errno) => return Err(errno.into()),
        }
        match mkdirat(&self.0, name, Mode::from_bits_truncate(0o700)) {
            Ok(()) | Err(Errno::EEXIST) => {}
            Err(errno) => return Err(errno.into()),
        }
        self.sync()?;
        Ok(Some(Self::admit(File::from(open()?))?))
    }
    /// Create a new owned 0600 file; an existing name is `Ok(None)`.
    pub fn create_file(&self, name: &str) -> Result<Option<File>> {
        debug_assert!(valid_name(name));
        match openat(
            &self.0,
            name,
            OFlag::O_RDWR | OFlag::O_CREAT | OFlag::O_EXCL | OFlag::O_NOFOLLOW | OFlag::O_CLOEXEC,
            Mode::from_bits_truncate(0o600),
        ) {
            Ok(fd) => {
                let file = File::from(fd);
                admit_file(&file, 1)?;
                Ok(Some(file))
            }
            Err(Errno::EEXIST) => Ok(None),
            Err(errno) => Err(errno.into()),
        }
    }
    /// Open an existing owned regular 0600 file with at most `max_links` names.
    pub fn open_file(&self, name: &str, max_links: u64) -> Result<Option<File>> {
        debug_assert!(valid_name(name));
        match openat(
            &self.0,
            name,
            OFlag::O_RDWR | OFlag::O_NOFOLLOW | OFlag::O_NONBLOCK | OFlag::O_CLOEXEC,
            Mode::empty(),
        ) {
            Ok(fd) => {
                let file = File::from(fd);
                admit_file(&file, max_links)?;
                Ok(Some(file))
            }
            Err(Errno::ENOENT) => Ok(None),
            Err(errno) => Err(errno.into()),
        }
    }
    /// Create-only hard link into `target`; `false` means the destination name already exists.
    pub fn link_into(&self, name: &str, target: &Self, target_name: &str) -> Result<bool> {
        debug_assert!(valid_name(name) && valid_name(target_name));
        match linkat(&self.0, name, &target.0, target_name, AtFlags::empty()) {
            Ok(()) => Ok(true),
            Err(Errno::EEXIST) => Ok(false),
            Err(errno) => Err(errno.into()),
        }
    }
    /// Remove one exact file name; `false` when it was already absent.
    pub fn unlink(&self, name: &str) -> Result<bool> {
        debug_assert!(valid_name(name));
        match unlinkat(&self.0, name, UnlinkatFlags::NoRemoveDir) {
            Ok(()) => Ok(true),
            Err(Errno::ENOENT) => Ok(false),
            Err(errno) => Err(errno.into()),
        }
    }
    /// Remove one exact empty directory; `false` when it was already absent.
    pub fn remove_dir(&self, name: &str) -> Result<bool> {
        debug_assert!(valid_name(name));
        match unlinkat(&self.0, name, UnlinkatFlags::RemoveDir) {
            Ok(()) => Ok(true),
            Err(Errno::ENOENT) => Ok(false),
            // A foreign entry inside: keep it and report the tree as not cleanly removable.
            Err(Errno::ENOTEMPTY | Errno::EEXIST) => Err(TreeError::Unsafe),
            Err(errno) => Err(errno.into()),
        }
    }
    pub fn sync(&self) -> Result<()> {
        self.0.sync_all().map_err(Into::into)
    }
}

/// Owned regular 0600 file with at most `max_links` directory entries.
pub fn admit_file(file: &File, max_links: u64) -> Result<()> {
    let metadata = file.metadata()?;
    if !metadata.is_file()
        || metadata.uid() != Uid::effective().as_raw()
        || metadata.mode() & 0o777 != 0o600
        || metadata.nlink() == 0
        || metadata.nlink() > max_links
    {
        return Err(TreeError::Unsafe);
    }
    Ok(())
}
pub fn len(file: &File) -> Result<u64> {
    Ok(file.metadata()?.len())
}
pub fn read_at(file: &File, offset: u64, buffer: &mut [u8]) -> Result<()> {
    file.read_exact_at(buffer, offset).map_err(Into::into)
}
pub fn write_at(file: &File, offset: u64, bytes: &[u8]) -> Result<()> {
    file.write_all_at(bytes, offset).map_err(Into::into)
}
