[package]
workspace = "../../../../rust"
name = "tmt-colab"
version = "0.1.0-alpha.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[package.metadata.dist]
dist = false

[dependencies]
ed25519-dalek.workspace = true
getrandom.workspace = true
nix.workspace = true
rusqlite.workspace = true
sha2.workspace = true

[lints]
workspace = true
