-- Remote schema 5, transcribed from origin/main commit 180295209.
-- Frozen legacy input for the schema 6 prefix migration; not generated by current product code.
CREATE TABLE _migrations(version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE machine(
             singleton INTEGER PRIMARY KEY CHECK(singleton = 1),
             machine_id TEXT NOT NULL,
             route_prefix TEXT NOT NULL);
INSERT INTO _migrations VALUES (1, 'machine', '2026-10-04T00:00:00Z');
CREATE TABLE grants(
             client_id TEXT PRIMARY KEY,
             public_key BLOB NOT NULL CHECK(length(public_key) = 32),
             kind TEXT NOT NULL CHECK(kind IN ('addon', 'browser', 'cli')),
             origin TEXT NOT NULL,
             name TEXT NOT NULL,
             agents TEXT NOT NULL,
             scopes TEXT NOT NULL,
             mode TEXT NOT NULL CHECK(mode IN ('direct', 'hold')),
             issued_at_ms INTEGER NOT NULL,
             expires_at_ms INTEGER,
             revision INTEGER NOT NULL CHECK(revision > 0),
             disabled INTEGER NOT NULL CHECK(disabled IN (0, 1)));
         -- One live grant per device key; a revoked key may pair again.
         CREATE UNIQUE INDEX grants_live_key ON grants(public_key) WHERE disabled = 0;;
INSERT INTO _migrations VALUES (2, 'grants', '2026-10-04T00:00:00Z');
CREATE TABLE sessions(
             client_id TEXT PRIMARY KEY REFERENCES grants(client_id),
             session_id TEXT NOT NULL UNIQUE,
             window_id TEXT NOT NULL,
             grant_revision INTEGER NOT NULL,
             next_client_sequence TEXT NOT NULL,
             next_server_sequence TEXT NOT NULL);
INSERT INTO _migrations VALUES (3, 'sessions', '2026-10-04T00:00:00Z');
CREATE TABLE streams(client_id TEXT PRIMARY KEY REFERENCES grants(client_id),
            incarnation TEXT NOT NULL, key BLOB NOT NULL, tip INTEGER NOT NULL DEFAULT 0,
            floor INTEGER NOT NULL DEFAULT 0, observed INTEGER NOT NULL DEFAULT 0,
            acknowledged INTEGER NOT NULL DEFAULT 0,last_ms INTEGER NOT NULL DEFAULT 0);
         CREATE TABLE entries(client_id TEXT NOT NULL REFERENCES streams(client_id),
            position INTEGER NOT NULL, envelope BLOB NOT NULL, at_ms INTEGER NOT NULL,
            PRIMARY KEY(client_id,position));
         CREATE TABLE operations(id TEXT PRIMARY KEY, client_id TEXT NOT NULL REFERENCES grants(client_id),
            operation TEXT NOT NULL, digest BLOB NOT NULL, frozen BLOB, phase TEXT NOT NULL,
            receipt TEXT NOT NULL, references_json TEXT NOT NULL DEFAULT '[]', updated_ms INTEGER NOT NULL);
         CREATE INDEX operations_client ON operations(client_id);
         CREATE TABLE budgets(subject TEXT NOT NULL,kind TEXT NOT NULL,started_ms INTEGER NOT NULL,
            used INTEGER NOT NULL,PRIMARY KEY(subject,kind));
         CREATE TABLE audit(position INTEGER PRIMARY KEY,at_ms INTEGER NOT NULL,
            client_id TEXT NOT NULL,envelope_id TEXT NOT NULL,operation TEXT NOT NULL,operation_id TEXT,resources_json TEXT NOT NULL,
            digest BLOB NOT NULL,grant_revision INTEGER NOT NULL,decision TEXT NOT NULL,code TEXT NOT NULL);;
INSERT INTO _migrations VALUES (4, 'journal', '2026-10-04T00:00:00Z');
CREATE TABLE door_port(
             singleton INTEGER PRIMARY KEY CHECK(singleton = 1),
             port INTEGER NOT NULL CHECK(port BETWEEN 1 AND 65535));
INSERT INTO _migrations VALUES (5, 'door_port', '2026-10-04T00:00:00Z');
