[package]
workspace = "../../../../rust"
name = "tmt-office-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
tmt-adapters.workspace = true
tmt-core.workspace = true
tmt-office-model.workspace = true
rusqlite.workspace = true
base64.workspace = true
serde.workspace = true
sha2.workspace = true
nix.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["v4"] }

[lints]
workspace = true

[dev-dependencies]
png.workspace = true
